// <auto-generated />
namespace SauliBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shit));
        
        string IMigrationMetadata.Id
        {
            get { return "201710142232599_shit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
